{% set name = "chopin2" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a6e75dfbc5ec21b89098194045ab82fe54e660fc4293717d596635693345b86

build:
  number: 0
  noarch: python
  entry_points:
    - chopin2=chopin2.chopin2:chopin2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.16.3
    - pyspark >=2.40
    - numba >=0.51.2

test:
  imports:
    - chopin2
  commands:
    - pip check
    - chopin2 --version
  requires:
    - pip

about:
  home: https://github.com/cumbof/chopin2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: chopin2
  description: |
    Supervised Classification with Hyperdimensional Computing for massive datasets on commodity hardware.
    Supporting k-fold cross-validation and feature selection as backward variable elimination.

extra:
  recipe-maintainers:
    - cumbof
